apiVersion: batch/v1
kind: Job
metadata:
  name: etl-job
spec:
  template:
    spec:
      containers:
      - name: etl-job
        image: etl-job:latest
        imagePullPolicy: Never  
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      restartPolicy: Never
  backoffLimit: 2

